### ISSUE TITLE
Consider increasing the character limit (to 1000?)

### ISSUE THREAD

**Issue by nietaki** [genserver-social/community-tracker#3]
I knew the instance rules/configuration when I joined, so it's fair to just close this ticket, but I just want to make my case for increasing the character limit.

---

There's two main reasons I think the character limit increase makes sense:

The `@usernames@instance.social`, `#hasthags` and `[markdown style links](https://example.com)` all count towards the character limit - if you're writing a toot with a couple of links (to save others some googling), you're already limiting the amount of text you can write

I think the fediverse is uniquely positioned to facilitate some more thoughtful discussions than Twitter ever allowed for. A small character limit makes writing messages like "you're wrong, just use Node.js" much easier than providing some reasoning for your opinions - and splitting those across a number of messages is a crappy reading experience for the others.

I thought 500 characters would be just enough, but even writing my #introduction post I needed to spend a good amount of time editing to fit in the character limit. Similarly, listing some pros and cons in some conversation about some technology I had to skip some potentially relevant points or links *and* rephrase some points to fit in the character limit.

---

I do understand and agree we don't want to make the instance full of self-indulgent walls of text, but I feel increasing the character limit a bit (to 1000? 750?) could hit the optimal balance. 

I'd be happy to provide some more examples of reasonable looking posts from other instances that wouldn't fit the 500 character limits, if that would be helpful.

(below is the reply I was writing that prompted me to raise the issue after all)

![500](https://user-images.githubusercontent.com/140347/228833927-cca3af4f-0f46-4f8f-ad7b-7c7045bc261d.PNG)

**Comment by piisalie** [comment]
You make a solid case.  I like the forced terseness of the smaller limit, but hashtags and links do complicate things and I know a few people have had similar issues with intros. I have bumped it to 750 for the time being, we'll see how it fits. :)

**Comment by nietaki** [comment]
Thank you for giving it a try!
